[deploy]
startCommand = "gunicorn victimes_pesticides.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
