# Generated by Django 5.2.7 on 2025-11-05 02:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil", 'verbose_name_plural': "Pages d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='corps',
            field=wagtail.fields.StreamField([('paragraphe', 0), ('titre', 1), ('image', 2), ('appel_action', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3'], 'label': 'Paragraphe'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Titre de section'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Texte'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Lien', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titre', 3), ('texte', 4), ('lien', 5), ('texte_bouton', 6)]], {'label': "Appel à l'action"})}, verbose_name='Contenu principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text="Texte d'introduction de la page d'accueil", verbose_name='Introduction'),
        ),
    ]
