# Generated by Django 5.2.7 on 2025-11-06 00:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_corps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='corps',
            field=wagtail.fields.StreamField([('hero_block', 6), ('paragraphe', 7), ('titre', 8), ('image', 9), ('appel_action', 13)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image de fond'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre principal'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Lien du bouton', 'required': False}), 5: ('wagtail.blocks.IntegerBlock', (), {'default': 40, 'help_text': "Assombrit l'image pour améliorer la lisibilité du texte (0-80%)", 'label': "Opacité de l'overlay (%)", 'max_value': 80, 'min_value': 0}), 6: ('wagtail.blocks.StructBlock', [[('image_fond', 0), ('titre_principal', 1), ('sous_titre', 2), ('texte_bouton', 3), ('lien_bouton', 4), ('opacite_overlay', 5)]], {'icon': 'image', 'label': 'Bloc héro pleine largeur'}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3'], 'label': 'Paragraphe'}), 8: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Titre de section'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Texte'}), 12: ('wagtail.blocks.URLBlock', (), {'label': 'Lien', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('titre', 10), ('texte', 11), ('lien', 12), ('texte_bouton', 3)]], {'label': "Appel à l'action"})}, verbose_name='Contenu principal'),
        ),
    ]
