# Generated by Django 5.2.7 on 2025-11-05 02:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('message_remerciement', wagtail.fields.RichTextField(blank=True, help_text='Message affiché après la soumission du formulaire', verbose_name='Message de remerciement')),
            ],
            options={
                'verbose_name': 'Page de contact',
                'verbose_name_plural': 'Pages de contact',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Introduction qui apparaîtra en haut de la page', verbose_name='Introduction')),
                ('corps', wagtail.fields.StreamField([('paragraphe', 0), ('titre', 1), ('image', 2), ('citation', 3), ('appel_action', 8), ('html_brut', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'label': 'Paragraphe'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Titre de section'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Texte'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Lien', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('titre', 4), ('texte', 5), ('lien', 6), ('texte_bouton', 7)]], {'label': "Appel à l'action"}), 9: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Utiliser avec précaution', 'label': 'HTML brut'})}, verbose_name='Corps de la page')),
            ],
            options={
                'verbose_name': 'Page standard',
                'verbose_name_plural': 'Pages standards',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='pages_app.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
