# Generated by Django 5.2.7 on 2025-11-05 02:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualiteIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': "Page d'index des actualités",
                'verbose_name_plural': "Pages d'index des actualités",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('biographie', wagtail.fields.RichTextField(blank=True, verbose_name='Biographie')),
                ('courriel', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
            },
        ),
        migrations.CreateModel(
            name='ActualitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_publication', models.DateField(help_text="Date à laquelle l'actualité sera publiée", verbose_name='Date de publication')),
                ('introduction', models.TextField(blank=True, help_text='Court résumé qui apparaîtra dans les listes', verbose_name='Introduction')),
                ('corps', wagtail.fields.StreamField([('paragraphe', 0), ('titre', 1), ('image', 2), ('citation', 3), ('code', 4), ('html_brut', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Paragraphe'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Titre de section'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Bloc de code', 'label': 'Code'}), 5: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Utiliser avec précaution', 'label': 'HTML brut'})}, verbose_name="Corps de l'article")),
                ('mise_en_vedette', models.BooleanField(default=False, help_text="Afficher dans la section vedette de la page d'accueil", verbose_name='Mise en vedette')),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to='actualites.auteur', verbose_name='Auteur')),
                ('categories', models.ManyToManyField(blank=True, to='actualites.categorie', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
            },
            bases=('wagtailcore.page',),
        ),
    ]
