# Generated by Django 5.2.7 on 2026-01-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitepage',
            name='image_principale',
            field=models.ForeignKey(blank=True, help_text="Image optionnelle affichée dans la liste des actualités et en haut de l'article (recommandé: format paysage, min. 1200x800px)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de prévisualisation'),
        ),
    ]
