# Generated by Django 5.2.7 on 2026-05-08 22:02

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_alter_actualitepage_image_principale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='actualites.categorie', verbose_name='Catégories'),
        ),
    ]
